version: '3.8'

services:
  mc:
    restart: always
    image: itzg/minecraft-server:java8
    volumes:
    - ../modpacks:/data/modpacks:ro
    - ../FeedTheBeast:/data/FeedTheBeast:rw
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      VERSION: 1.10.2
      CF_SERVER_MOD: modpacks/FarmingValleyServer_103.zip
      OPS: minejakkaj,jakpower
      WHITELIST: TheFondEmperor,minejakkaj,jakpower
    ports:
      - 25500:25565