version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:java8-multiarch
    volumes:
    - ../modpacks:/data/modpacks:ro
    - ../FeedTheBeast:/data/FeedTheBeast:rw
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      VERSION: 1.10.2
      CF_SERVER_MOD: modpacks/FarmingValleyServer_103.zip
    ports:
      - 25500:25500